@me = [field:global.autoindex/];
                    <li>
                        <dl>

                            <dd>
                                <a href="[field:arcurl/]" target="_blank"><img src="[field:picname/]" /></a>
                                <h3><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h3>
                                <p>[field:description function="cn_substr(@me,400)"/]...</p>
                            </dd>


                        </dl>
                    </li>