<li>
                        <dl>
                            <dd>
                                <a href="news_detail.html" target="_blank"><img src="[field:picname/]" /></a>
                                <h3><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h3>
                                <p>[field:description function="cn_substr(@me,400)"/]...</p>
                            </dd>
                            <!-- <dd>
                                <a href="news_detail.html" target="_blank"><img src="{dede:global.cfg_basehost/}/style/img/news.png" /></a>
                                <h3><a href="news_detail.html" target="_blank">企事业单位班车</a></h3>
                                <p>法国企业界有一句名言：“爱你的员工吧，他会百倍地爱你的企业。”</p>
                            </dd>
                             <dd>
                                <a href="news_detail.html" target="_blank"><img src="{dede:global.cfg_basehost/}/style/img/news.png" /></a>
                                <h3><a href="news_detail.html" target="_blank">企事业单位班车</a></h3>
                                <p>法国企业界有一句名言：“爱你的员工吧，他会百倍地爱你的企业。”</p>
                            </dd> -->

                        </dl>
                    </li>